# Generated by Django 4.1.3 on 2023-01-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_fruit_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='pics')),
                ('profile', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Fruit',
        ),
    ]
